### ISSUE TITLE
question: It this pkg compatible with RN 0.60.x?

### ISSUE THREAD

**Issue by leonardoanalista** [naoufal/react-native-touch-id#249]
Question: It this pkg compatible with RN 0.60.x?

I ma getting this error: 
`
❌  clang: error: no such file or directory: '/Users/vagrant/Library/Developer/Xcode/DerivedData/[REDACTED]-amqyxfvxotkathehguapaggayebn/Build/Intermediates.noindex/ArchiveIntermediates/Test/BuildProductsPath/Test-iphoneos/libTouchID.a'
`
I am still working to figure out. I'll post here if I fix it.

**Comment by stockrel** [comment]
+1

**Comment by MaximeConan** [comment]
It works for me (RN 0.60.5 and RN Touch Id 4.4.1).

You should try to delete the import of `libTouchId.a` in your XCode : 

- Remove the library from `Build Settings > Header Search Paths`
- Remove the library from ` Build Phases > Link Binary With Libraries`
- Remove the library from the folder `Libraries` in your left panel

After it, add this line `pod 'TouchID', :path => '../node_modules/react-native-touch-id'` to your Podfile, then `cd ios && pod install`

This is beacause of now the libraries are linked automatically since 0.60.x

It should do the job !

**Comment by leonardoanalista** [comment]
awesome thank you. I'll close this issue. 👍
