### ISSUE TITLE
touch id no longer supported if user fails to authenticate too many times

### ISSUE THREAD

**Issue by stantoncbradley** [naoufal/react-native-touch-id#48]
Thanks for the great lib!

If a user enters an invalid touch too many times, touch id is permanently no longer supported for the app.  Is this intended behavior?  Seems like strange behavior and in our case not desirable.  Any insight into this?

Ideally I think, it would be up to application devs if we want to disable touch support on too many failures.  or at least there should be a way to enable it again?

Thanks!!!

**Comment by zibs** [comment]
I could be wrong, but I think this is baked into how iOS implements Touch ID. 

You can reproduce this behaviour simply by trying to log into your phone. If you fail three times, then you have to re-enter your passcode before you can re-enable Touch ID. 

It seems to me that one fails to successfully authenticate after three attempts, iOS disables Touch ID support until the user has re-enabled it by entering in their passcode.

I'd love to know if you know any way around this, or have heard otherwise.

**Comment by stantoncbradley** [comment]
@zibs that makes sense.  I tried on another app (LastPass) and after failing to authenticate, it said I could reenable it from Settings, but I didn't see the option.  This library does not seem to support re-enabling, would be a great feature.  Again, not sure what support for this looks like on the native ios level

**Comment by naoufal** [comment]
Would you mind posting screenshots or linking to official Apple TouchID
documentation?

**Comment by stantoncbradley** [comment]
@naoufal did you see the update to my comment?  not seeing anything relevant in the docs or general google searching.  here is the alert from lastpass:
![image](https://user-images.githubusercontent.com/5314103/29948636-d73bef62-8e64-11e7-9593-43f7eb8e5cb1.png)
