### ISSUE TITLE
[Android] OptionalConfigObject not so optional...

### ISSUE THREAD

**Issue by hkung77** [naoufal/react-native-touch-id#87]
I tried to authenticate without the config object on android and the app crashes.

`AndroidRuntime: com.facebook.react.bridge.NoSuchKeyException: couldn't find key title in dynamic object
AndroidRuntime: at com.facebook.react.bridge.ReadableNativeMap.getString(Native Method)
AndroidRuntime: at com.rnfingerprint.FingerprintDialog.onCreateView(FingerprintDialog.java:45)
`

**Comment by zibs** [comment]
Seems to me you might still be passing in an empty object or something. If you look at the code https://github.com/naoufal/react-native-touch-id/blob/32617a03b26a8da850c0f1c5f7b49a03affa5791/TouchID.android.js#L22 here you can see that if you don't pass in any object at all, it will default back to this default config object. Otherwise, it's going to use whatever you send in.

Feel free to provide a sample of your code and I can take a look

**Comment by hkung77** [comment]
Ahh! thank you for the response! Yea I can understand what's happening now. I was passing in an empty object. I presumed the value's themselves would be optional if the values weren't found.
